name: Deploy Website ABCFunLearn

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy ABCFunLearn to server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.IP_SERVER }}
        username: ${{ secrets.USER_SERVER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 777
        script: |
          cd /var/www/abcfunlearn
          git fetch origin
          git reset --hard origin/main
          sudo systemctl reload nginx

